name: foodly
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  mobx: ^2.0.7+3
  flutter_mobx: ^2.0.6+1
  flutter_hooks: ^0.18.5
  faker: ^2.0.0
  carousel_slider: ^4.1.1
  sliver_tools: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:  
  uses-material-design: true
  assets: 
    - asset/icons/
    - asset/images/Intro/
    - asset/images/Food/Carousel/
    - asset/images/Food/Featured/
    - asset/images/Banners/
    - asset/images/Food/Horizontal/
    - asset/images/Header/
    - asset/images/ItemDetails/

  fonts:
    - family: SF-PRO
      fonts:
        - asset: asset/fonts/SF Pro Text Bold.ttf
        - asset: asset/fonts/SF Pro Text Light.ttf
        - asset: asset/fonts/SF Pro Text Medium.ttf
        - asset: asset/fonts/SF Pro Text Regular.ttf
        - asset: asset/fonts/SF Pro Text Semibold.ttf
        - asset: asset/fonts/SF Pro Text Thin.ttf
